# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sports',
        ),
        migrations.AddField(
            model_name='customer',
            name='sports',
            field=models.ManyToManyField(to='customers_admin_app.Sport'),
        ),
    ]
